sudo: required
dist: trusty
language: generic
env:
  - ROS_DISTRO="indigo"
  - ROS_DISTRO="kinetic"
  - ROS_DISTRO="melodic"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
